// <auto-generated />
namespace EventAdmin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixissueOnMaxLenght : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixissueOnMaxLenght));
        
        string IMigrationMetadata.Id
        {
            get { return "202004100152307_fixissueOnMaxLenght"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
